DROP TABLE IF EXISTS noteful_cards;

CREATE TABLE noteful_cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_modified DATE,
    title TEXT NOT NULL,
    content TEXT,
    folder INTEGER REFERENCES noteful_folders(id) NOT NULL
);